### PR TITLE
RNG Reproducibility

### PR DESCRIPTION
**Pull request by proofconstruction**
As discussed in #9 , it will be useful for testing purposes to control the degree of nondeterminism in the library.

To accomplish that goal, this PR does the following:
1. Removes all dependencies on `numpy.random` and replaces them with equivalent uses of `random.random` from Python's stdlib.
2. Updates `README.md` to:
    1. note the library's dependency only on `random.random` for random number generation,
    2. provide information about how to set the random seed to control this, and
    3. include links to useful documentation.

### CODE REVIEW

**Comment by jboarman** [comment]
Looks great!

**Comment by kwcckw** [comment]
> 
> 
> As discussed in #9 , it will be useful for testing purposes to control the degree of nondeterminism in the library.
> 
> To accomplish that goal, this PR does the following:
> 
>     1. Removes all dependencies on `numpy.random` and replaces them with equivalent uses of `random.random` from Python's stdlib.
> 
>     2. Updates `README.md` to:
>        
>        1. note the library's dependency only on `random.random` for random number generation,
>        2. provide information about how to set the random seed to control this, and
>        3. include links to useful documentation.

Thanks, i will try this out.

**Comment by kwcckw** [comment]
i tried but looks like sometimes the results are not consistent when p is not set as 1. 

This is the modified default pipeline:

    ink_phase = AugmentationSequence([
                                  FoldingAugmentation(p=0.5),
                                  BleedThroughAugmentation(p=0.5),
                                  InkBleedAugmentation(p=0.5),
                                  DustyInkAugmentation(p=0.5),
                                  LowInkBlobsAugmentation(p=0.5),
                                  OneOf([
                                    LowInkRandomLinesAugmentation(use_consistent_lines=False,p=0.5),
                                    LowInkRandomLinesAugmentation(use_consistent_lines=True,p=0.5),
                                    LowInkPeriodicLinesAugmentation(use_consistent_lines=False,p=0.5),
                                    LowInkPeriodicLinesAugmentation(use_consistent_lines=True,p=0.5),
                                  ]),
                                  GaussianBlurAugmentation('ink', p=0.5)
                                ])

    paper_phase = AugmentationSequence([PaperFactory(),
                                        OneOf([
                                        AugmentationSequence([
                                            NoiseTexturizeAugmentation(p=0.5),
                                            BrightnessTexturizeAugmentation(p=0.5),
                                            GaussianBlurAugmentation('paper', [(3,3), (3,5), (5,3), (5,5)],p=0.5),
                                            ]),
                                        AugmentationSequence([
                                            BrightnessTexturizeAugmentation(p=0.5),
                                            NoiseTexturizeAugmentation(p=0.5),
                                            GaussianBlurAugmentation('paper', [(3,3), (3,5), (5,3), (5,5)],p=0.5),
                                        ])]),
                                        BrightnessAugmentation('paper',p=0.5)
                                ])


    post_phase = AugmentationSequence([DirtyRollersAugmentation(p=0.0),
                                    OneOf([
                                            LightingGradientAugmentation(p=0.5),
                                            BrightnessAugmentation('post',p=0.5)
                                        ]),
                                        SubtleNoiseAugmentation(p=0.5),
                                        JpegAugmentation(p=0.5)
                                        ])

                                        
1st trial:
image

2nd trial:
image

The test code:

          import string
          import random
          import cv2
          import numpy as np
          import PIL
          import os
          from pdf417gen import encode, render_image
          random.seed(2)
          
          from augraphy.base.augmentationpipeline import AugraphyPipeline
          from augraphy.default.pipeline import default_augraphy_pipeline
          from augraphy.augmentations import *
          
          
          img = cv2.imread('test_img.png')
          
          pipeline = default_augraphy_pipeline()
          
          
          for i in range(2):
              crappified = pipeline.augment(img)
              dim = crappified["output"].shape
              resized=cv2.resize(crappified["output"], (int(dim[0]/2),int(dim[1]/2)), interpolation = cv2.INTER_AREA)
              cv2.imshow(str(i), resized)
              cv2.waitKey(1)

I think somewhere else there's a section is still using numpy.random, need to further check on this.

**Comment by proofconstruction** [comment]
The `default_augraphy_pipeline()` is very random; most augmentations have probability 0.5 and these are not values chosen from the Mersenne twister sequence used by `random.random`. If we build a new pipeline where **every** augmentation has `p=1` (or `force=True`), and use parameters that prevent the `AugraphyPipeline` from randomly selecting more stuff.

Here's a modified script which defines a new pipeline and restricts more of the probability:
```
import string
import random
import cv2
import numpy as np
import PIL
import os

from augraphy.base.paperfactory import PaperFactory
from augraphy.base.oneof import OneOf
from augraphy.base.augmentationsequence import AugmentationSequence
from augraphy.base.augmentationpipeline import AugraphyPipeline

from augraphy.augmentations.brightness import BrightnessAugmentation
from augraphy.augmentations.brightnesstexturize import BrightnessTexturizeAugmentation
from augraphy.augmentations.dirtyrollers import DirtyRollersAugmentation
from augraphy.augmentations.dustyink import DustyInkAugmentation
from augraphy.augmentations.gaussianblur import GaussianBlurAugmentation
from augraphy.augmentations.inkbleed import InkBleedAugmentation
from augraphy.augmentations.jpeg import JpegAugmentation
from augraphy.augmentations.lightinggradient import LightingGradientAugmentation
from augraphy.augmentations.lowinkblobs import LowInkBlobsAugmentation
from augraphy.augmentations.lowinkperiodiclines import LowInkPeriodicLinesAugmentation
from augraphy.augmentations.lowinkrandomlines import LowInkRandomLinesAugmentation
from augraphy.augmentations.noisetexturize import NoiseTexturizeAugmentation
from augraphy.augmentations.subtlenoise import SubtleNoiseAugmentation

random.seed(2)

img = cv2.imread("test.png")

ink_phase = AugmentationSequence([
                              InkBleedAugmentation(p=1),
                              DustyInkAugmentation(p=1),
                              LowInkBlobsAugmentation(p=1),
                              OneOf([
                                LowInkRandomLinesAugmentation(use_consistent_lines=False, p=1),
                                LowInkRandomLinesAugmentation(use_consistent_lines=True, p=1),
                                LowInkPeriodicLinesAugmentation(use_consistent_lines=False, p=1),
                                LowInkPeriodicLinesAugmentation(use_consistent_lines=True, p=1),
                              ], p=1),
                              GaussianBlurAugmentation('ink', p=1)
                            ])

paper_phase = AugmentationSequence([PaperFactory(),
                                    OneOf([
                                    AugmentationSequence([
                                        NoiseTexturizeAugmentation(p=1),
                                        BrightnessTexturizeAugmentation(p=1),
                                        GaussianBlurAugmentation('paper', [(3,3), (3,5), (5,3), (5,5)], p=1),
                                        ], p=1),
                                    AugmentationSequence([
                                        BrightnessTexturizeAugmentation(p=1),
                                        NoiseTexturizeAugmentation(p=1),
                                        GaussianBlurAugmentation('paper', [(3,3), (3,5), (5,3), (5,5)], p=1),
                                    ])], p=1),
                                    BrightnessAugmentation('paper', p=1)
                            ])


post_phase = AugmentationSequence([DirtyRollersAugmentation(p=0.0),
                                OneOf([
                                        LightingGradientAugmentation(p=1),
                                        BrightnessAugmentation('post', p=1)
                                    ], p=1),
                                    SubtleNoiseAugmentation(p=1),
                                    JpegAugmentation(p=1)
                                    ])

pipeline = AugraphyPipeline(ink_phase,
                            paper_phase,
                            post_phase,
                            ink_color_range=(0,0),
                            paper_color_range=(255,255),
                            rotate_range=(0,0)
                            )


for i in range(10):
    crappified = pipeline.augment(img)
    dim = crappified["output"].shape
    resized=cv2.resize(crappified["output"], (int(dim[0]/2),int(dim[1]/2)), interpolation = cv2.INTER_AREA)
    cv2.imwrite(str(i) + ".jpg", resized)
```

Using this, I was able to produce the same results in 5 separate tests (copied the whole augraphy directory to test1, test2, ..., test5 directories and ran src/test.py in each).

**Comment by kwcckw** [comment]
Yes, with p set to 1, i was able to reproduce the same outcome. 

> most augmentations have probability 0.5 and these are not values chosen from the Mersenne twister sequence used by random.random

Then shouldn't we change all value to use generated value from random.random?

Since with fixed random seed, we should be able to reproduce a same result, and i think reproducibility is very important.

**Comment by proofconstruction** [comment]
> Then shouldn't we change all value to use generated value from random.random?
> 
> Since with fixed random seed, we should be able to reproduce a same result, and i think reproducibility is very important.

We almost do this already, but in the opposite order. Right now, we set `p=0.5` [in every augmentation](https://github.com/sparkfish/augraphy/blob/dev/src/augraphy/base/augmentation.py#L12) and then check if [a random number in the interval [0,1] is <= 0.5](https://github.com/sparkfish/augraphy/blob/dev/src/augraphy/base/augmentation.py#L24). We could turn this around and let the default `p=random.randint(0,1)` and change the `should_run` method to
```
    def should_run(self):
        return random.choice([True, False])
```
or maybe `bool(random.randint(0,1))`, but I don't think this really matters.

We already use random numbers for this, but the numbers are generated far away in the Augmentations class, so it's harder to think about ([other libraries also do this](https://github.com/albumentations-team/albumentations/blob/master/albumentations/augmentations/transforms.py#L125)). This is why in #22 I wanted to remove probability from augmentations and put it into the pipeline instead :smile:

**Comment by kwcckw** [comment]
> This is why in #22 I wanted to remove probability from augmentations and put it into the pipeline instead 😄

i see, but if we put it in the pipeline, are we still able to control `p` of each individual augmentation?

**Comment by jboarman** [comment]
I agree.  We need to be sourcing from the same generator instance sharing the same seed across all calls.  How is this problem managed in the other augmentation libs?

**Comment by proofconstruction** [comment]
> i see, but if we put it in the pipeline, are we still able to control `p` of each individual augmentation?

Yes. We would have to add this functionality but it wouldn’t be too hard. I can do it tomorrow. 

> I agree. We need to be sourcing from the same generator instance sharing the same seed across all calls. How is this problem managed in the other augmentation libs?

Other libs just set the seed like we’ve done above.

If you’re already familiar with how seeding the RNG works, skip the rest of this message, but otherwise it goes like this: if the random seed is set, the numbers generated by every successive call to the random object  _in the same process_  are determined. Essentially, there’s a predefined sequence of numbers which the random object stores a cursor pointing into, and when you set the random seed, you specify the starting position for that cursor (technically, you specify the initial _previous_ value). Every call afterwards returns the element at the cursor location and advances the cursor one position in the sequence. By specifying the seed, we can move the cursor back to the same position in the sequence every time the program is run, and this has the practical effect of generating the same “random” numbers every time.

**Comment by jboarman** [comment]
It sounds like we are just getting confused ... a solid example notebook demonstrating any unexpected results is probably the best place to resolve any confusion.  To me, this sounds like it may just come down to where the seed is being set to guarantee 2 separate runs produce the same result.

**Comment by kwcckw** [comment]
> To me, this sounds like it may just come down to where the seed is being set to guarantee 2 separate runs produce the same result.

Yes, that should be the case, so that we can reproduce same result if needed. But in a single run, we should get random result in a loop:

For example, the code:

        import random
        random.seed(1)
        for i in range(10):
            print(random.random())
            
With seed = 1, we will get the same random result below in every run:

      0.13436424411240122
      0.8474337369372327
      0.763774618976614
      0.2550690257394217
      0.49543508709194095
      0.4494910647887381
      0.651592972722763
      0.7887233511355132
      0.0938595867742349
      0.02834747652200631

**Pull request merged**
