### PR TITLE
Added cv_blend

### PR DESCRIPTION
**Pull request by kwcckw**

### CODE REVIEW

**Comment by kwcckw** [comment]
With this added `cv_blend`, i think this is somehow similar with the current overlay function, so i think we can consolidate them into 1 file or 1 function with option to select different kinds of blending or overlay methods?

**Comment by proofconstruction** [comment]
I think 1 function with multiple options is best, in case we have a reason to use the old feature/code. We can always remove it later.

Can you add some example code and a picture here? And also add the Markdown documentation?

**Comment by kwcckw** [comment]
> 
> 
> I think 1 function with multiple options is best, in case we have a reason to use the old feature/code. We can always remove it later.

Alright, then this can be included in the overlay builder later.

> 
> Can you add some example code and a picture here? And also add the Markdown documentation?

The markdown doc should be already included here right?

image

Here's the snippet of code and output example:

        img_source = cv2.imread('best_copy.png')
        img_background = cv2.imread('img_34123.png')
        
        ysize, xsize = img_background.shape[:2]
        
        # blend to centroid of background
        center = [int(xsize/2), int(ysize/2)] 
        
        img_blend = cv_blend(img_source, img_background, center=center, blend_type=cv2.MIXED_CLONE)
        
        plt.figure()
        plt.imshow(cv2.cvtColor(img_blend, cv2.COLOR_BGR2RGB))
        plt.title('Blended image')

        plt.figure()
        plt.imshow(cv2.cvtColor(img_source, cv2.COLOR_BGR2RGB))
        plt.title('Source')
        
        plt.figure()
        plt.imshow(cv2.cvtColor(img_background, cv2.COLOR_BGR2RGB))
        plt.title('Background')
        

Examples:
image

image

image

**Comment by proofconstruction** [comment]
Can you run `pre-commit run --all-files` locally and then push again? There were some lines that Black and another pinter rewrote.

**Comment by kwcckw** [comment]
> 
> 
> Can you run `pre-commit run --all-files` locally and then push again? There were some lines that Black and another pinter rewrote.

Yea, i did rerun it several times but i didn't facing any issue:

image

There's no changes for new commit too. Do you have any idea on the problem?

**Comment by proofconstruction** [comment]
It fixed the array formatting; each dimension of the array indices should go on a separate line.

```
Add trailing commas......................................................Failed
- hook id: add-trailing-comma
- exit code: 1
- files were modified by this hook

Rewriting augraphy/augmentations/lib.py

black....................................................................Failed
- hook id: black
- files were modified by this hook

reformatted augraphy/augmentations/lib.py
All done! ✨ 🍰 ✨
1 file reformatted, 46 files left unchanged.

flake8...................................................................Passed
pre-commit hook(s) made changes.
If you are seeing this message in CI, reproduce locally with: `pre-commit run --all-files`.
To run `pre-commit` as part of git workflow, use `pre-commit install`.
All changes made by hooks:
diff --git a/augraphy/augmentations/lib.py b/augraphy/augmentations/lib.py
index d14702b..3d7f325 100644
--- a/augraphy/augmentations/lib.py
+++ b/augraphy/augmentations/lib.py
@@ -334,7 +334,8 @@ 
```
```python
def cv_blend(img_source, img_background, center=None, blend_type=cv2.MIXED_CLONE
     # if source size is > background size, crop only the fitting size
     if center_y - ysize_half_source < 0 and center_y + ysize_half_source > ysize_background:
         img_source = img_source[
-            -(center_y - ysize_half_source) : ysize_source - (center_y + ysize_half_source - ysize_background), :
+            -(center_y - ysize_half_source) : ysize_source - (center_y + ysize_half_source - ysize_background),
+            :,
         ]
         # new size after cropping
         # source size
```
```
@@ -344,7 +345,8 @@
```
```python
def cv_blend(img_source, img_background, center=None, blend_type=cv2.MIXED_CLONE
 
     if center_x - xsize_half_source < 0 and center_x + xsize_half_source > xsize_background:
         img_source = img_source[
-            :, -(center_x - xsize_half_source) : xsize_source - (center_x + xsize_half_source - xsize_background)
+            :,
+            -(center_x - xsize_half_source) : xsize_source - (center_x + xsize_half_source - xsize_background),
         ]
         # new size after cropping
         # source size
```

**Comment by kwcckw** [comment]
> 
> 
> It fixed the array formatting; each dimension of the array indices should go on a separate line.
> 

I see, it's weird that it didn't fix the issue when i run it, thanks for the help.

**Comment by jboarman** [comment]
I was motivated by this thread to do some minor reading on blend modes and found these sources interesting:

* https://github.com/flrs/blend_modes
* https://docs.gimp.org/en/gimp-concepts-layer-modes.html
* https://blend-modes.readthedocs.io/en/latest/visual_examples.html

The source code in that FLRS "Blend Modes" Python package implements various techniques.  That package does not seem to be maintained, but the number of lines is really small if we wanted to ~borrow~ steal some of their code (and include proper attribution).

**Comment by kwcckw** [comment]
> I was motivated by this thread to do some minor reading on blend modes and found these sources interesting:
> 
>     * https://github.com/flrs/blend_modes
> 
>     * https://docs.gimp.org/en/gimp-concepts-layer-modes.html
> 
>     * https://blend-modes.readthedocs.io/en/latest/visual_examples.html
> 
> 
> The source code in that FLRS "Blend Modes" Python package implements various techniques. That package does not seem to be maintained, but the number of lines is really small if we wanted to ~borrow~ steal some of their code (and include proper attribution).

Thanks, this should be very helpful. I will need to test through them out first, since i don't think we need all of the blending methods there, some of them might not relevant in our use case.

**Pull request merged**
