### PR TITLE
Added Text Strikethrough

### PR DESCRIPTION
**Pull request by shaheryar1**
Added Text Strikethrough #63  in `ink `phase. The pencil texture has not been added yet. I am waiting for it to be available in shared lib.

### CODE REVIEW

**Comment by proofconstruction** [comment]
There are a lot of changes here. It looks like some of the pre-commit changes to the code are spread across several commits somehow.

I have a few questions:
1. Why did you remove the version requirement from `numpy` in `requirements.txt`?
2. Why did you add and remove `bookbinding.md`?

I'm happy to merge the new `strikethrough.py` but I want to avoid these other commits that contain the pre-commit changes we already have in the commit history. Can you delete your version of the repository and fork sparkfish/augraphy again, and then make a new PR with just the `strikethrough.py`?

**Comment by shaheryar1** [comment]
1. For numpy pip3 wasn't able to find any version greater than 1.9
2. I removed bookbinding.md documentation as I thought the failed test are because of that file ( it was the issue of pre-commit )

I guess the other files were not modified by pre-commit earlier and running my pre-commit changed those. 

I'll look for some solution for this tonight

**Comment by shaheryar1** [comment]
I guess I should've pushed my changes only which were related to strikethrough.py.

**Comment by proofconstruction** [comment]
> For numpy pip3 wasn't able to find any version greater than 1.9

Where did you see this error?

> I removed bookbinding.md documentation as I thought the failed test are because of that file ( it was the issue of pre-commit )

In the future, you can `git add` the files you want to commit, then `pre-commit run --all-files` *before* you commit, and it will fix the files first.

> I guess I should've pushed my changes only which were related to strikethrough.py.

Yeah, let's try to keep commits small and only do a few things at a time. Big PRs are hard to look through :grin:

**Comment by proofconstruction** [comment]
If you submit a pull request for just the changes related to `strikethrough.py`, I'll go ahead and merge it. Closing this one for now though.

**Pull request closed without merging**
