### PR TITLE
re-commit badphotocopy update

### PR DESCRIPTION
**Pull request by kwcckw**

### CODE REVIEW

**Comment by kwcckw** [comment]
@proofconstruction  i detached the fork and re-commit those updates but looks like i'm facing a new error in those checks, could you advise again?

image

**Comment by proofconstruction** [comment]
black and the trailing comma hook are reformatting badphotocopy.py, you can try to run `pre-commit run --all-files` locally to fix the file and then commit again. It looks like the change is in the init method of that class; black wants us to use a new line for each parameter, and the pre-commit hook adds a comma character after the last parameter

**Comment by kwcckw** [comment]
> 
> 
> black and the trailing comma hook are reformatting badphotocopy.py, you can try to run `pre-commit run --all-files` locally to fix the file and then commit again. It looks like the change is in the init method of that class; black wants us to use a new line for each parameter, and the pre-commit hook adds a comma character after the last parameter

Thanks, it resolved the error.

**Comment by proofconstruction** [comment]
Good - I added some more info about this [here](https://github.com/sparkfish/augraphy/blob/dev/doc/contributing.md)

**Pull request merged**
