### PR TITLE
Documentation Update

### PR DESCRIPTION
**Pull request by amitbcp**
**Problem Faced** : While using the repo, it took some time to go through all the available augmentations and there examples as many markdowns don't have sample results, and many Colab's examples throw and error due to code changes in the repo

**PR** : This PR will update all the existing augmentations with examples and Colab, while adding any missing augmentation as well

Currently only a sample addition was done to test the setup and PR

@proofconstruction @kwcckw @jboarman  let me know if it will be helpful, they I can go ahead and update the augmentation usage accordingly

### CODE REVIEW

**Comment by kwcckw** [comment]
> **Problem Faced** : While using the repo, it took some time to go through all the available augmentations and there examples as many markdowns don't have sample results, and many Colab's examples throw and error due to code changes in the repo
> 
> **PR** : This PR will update all the existing augmentations with examples and Colab, while adding any missing augmentation as well
> 
> Currently only a sample addition was done to test the setup and PR
> 
> @proofconstruction @kwcckw @jboarman let me know if it will be helpful, they I can go ahead and update the augmentation usage accordingly

Sorry some of the docs are not updated yet, but i think it might be too memory consuming if we add example images for all augmentations. At this moment, i think it's good to just update those docs.

**Comment by amitbcp** [comment]
@kwcckw cool, will do that. though we can also push images to LFS if space is a concern, as the images are not more than 50-100Kb

will update the Colab and notes till then

**Comment by kwcckw** [comment]
> @kwcckw cool, will do that. though we can also push images to LFS if space is a concern, as the images are not more than 50-100Kb
> 
> will update the Colab and notes till then

 Thanks ! For now i think just updating the colab will be good. But are you able to edit the colab files in the doc?

**Comment by amitbcp** [comment]
@kwcckw no if I edit the existing Colab and save, it will save a new copy. So I am updating Colab with the new notebook links as I test them

**Comment by kwcckw** [comment]
> @kwcckw no if I edit the existing Colab and save, it will save a new copy. So I am updating Colab with the new notebook links as I test them

I see, could you share me those links once they are updated? I will go through them first and update them accordingly.

**Comment by amitbcp** [comment]
sure

**Comment by jboarman** [comment]
@amitbcp Hi there ... I really want to be able to merge in your PR.  Can you pull in the latest version from the `dev` branch and resolve conflicts so that we can close out this PR?

If you are not available for that, let me know and we can close out this PR if you prefer.

**Comment by amitbcp** [comment]
@jboarman sorry for the long delay. Let me complete this PR within this week. Thanks for the heads

**Comment by jboarman** [comment]
@amitbcp If you are able to resolve this conflict by Monday, I'd love to include you as an official contributor.   Otherwise, I will close this PR at that time.

**Comment by amitbcp** [comment]
@jboarman sorry for the delay. I am closing this ticket as all of changes in the repo have made the docs to .rst and the new docs are updated with the correct examples eliminating the Colab Notebooks

**Pull request closed without merging**
