### PR TITLE
Added BindingsAndFasteners and some other fixes. 

### PR DESCRIPTION
**Pull request by kwcckw**

### CODE REVIEW

**Comment by kwcckw** [comment]
Here's the examples from Figshare templates:
image

And here's the examples with some manually created effect:
image

**Comment by kwcckw** [comment]
There's some problem with the usage of `try-except`:

Is it possible to disable this requirement?
image

**Comment by proofconstruction** [comment]
This is great, nice work and thanks for cleaning up my mess :smile: 

> Is it possible to disable this requirement?

This was caused by only having `except:`. This is equivalent to `except Exception:`, which is the more correct way of writing this now [according to flake8](https://www.flake8rules.com/rules/E722.html).

**Comment by kwcckw** [comment]
> 
> 
> This is great, nice work and thanks for cleaning up my mess 😄
> 
> > Is it possible to disable this requirement?
> 
> This was caused by only having `except:`. This is equivalent to `except Exception:`, which is the more correct way of writing this now [according to flake8](https://www.flake8rules.com/rules/E722.html).

Thanks, this should be helpful in case we need to use `try-except` in the code.

Also where do you store those example notebooks for each augmentation? Could you share the folder containing those notebooks?

**Comment by proofconstruction** [comment]
> Also where do you store those example notebooks for each augmentation? Could you share the folder containing those notebooks?

Sure, send me an email to source@proof.construction so I can add you

**Pull request merged**
