### PR TITLE
Refactored badphotocopy and added sine pattern in noise with hash type = 1.

### PR DESCRIPTION
**Pull request by kwcckw**

### CODE REVIEW

**Comment by kwcckw** [comment]
Here's the example with added sine pattern:

image

So later we can further improve it by using different peak height in the sine wave, that would need some updates in the sine wave equation.

**Comment by proofconstruction** [comment]
This is a great start towards the effect in #61 - but it doesn't look very natural. Maybe if the period of the sine wave is much larger, it might be better.

We have a problem with GitHub though. Can you save the changes for this commit, and then delete your fork and re-fork the repository again? I try to squash merge these PRs to remove these messages: "Merge branch 'dev' of https://github.com/sparkfish/augraphy into dev", but when I squash merge, your branch and the main branch end up out of sync.

**Comment by proofconstruction** [comment]
Also, how do you make the choice for which part to apply the effect to?

**Comment by kwcckw** [comment]
> 
> 
> Also, how do you make the choice for which part to apply the effect to?

I'm checking pixel intensity of a small area at each corner, and then decide `side` of the noise, start from line 344.

Anyway, i will try to undo the commit and commit again, since I would need to contact github support if i need to detach the fork again, that would be more complicated.

**Comment by kwcckw** [comment]
> We have a problem with GitHub though. Can you save the changes for this commit, and then delete your fork and re-fork the repository again? I try to squash merge these PRs to remove these messages: "Merge branch 'dev' of https://github.com/sparkfish/augraphy into dev", but when I squash merge, your branch and the main branch end up out of sync.

I reverted the commit and pushed again the updates. Could you try again？

**Comment by proofconstruction** [comment]
> Anyway, i will try to undo the commit and commit again, since I would need to contact github support if i need to detach the fork again, that would be more complicated.

What I mean is, delete the fork, don't just detach it. Then fork the repo again, and push this commit to the new fork.

Right now your fork is 32 commits ahead, because all of your commits were squashed into one commit and merged into the main repo, but GitHub doesn't keep track of this information. This will only continue to increase, until you make pull requests with hundreds of commits.

To avoid the problem in the future, you can `git rebase` your local commits to squash the "merge branch dev" commit and your actual changes together.

**Pull request closed without merging**
