### PR TITLE
Added Markup class with markup type "underline" and "strikethrough"

### LINKED ISSUE #100: Markup class for strikethrough/underline
Should I create a `Markup`  ( as discussed in this [comment](https://github.com/sparkfish/augraphy/issues/63#issuecomment-919174591)) with the option to select between strikethrough, underline, or any other similar augmentation ?

### PR DESCRIPTION
**Pull request by shaheryar1**
We can remove the strikethrough.py now

### CODE REVIEW

**Comment by proofconstruction** [comment]
A few points:

1. `self.marktup_type` should be `self.markup_type`
2. can you try to add the highlighter effect from #103 ?
3. when a different type is given other than "strikethrough", the result is not an underline but an overline: 

markup

**Comment by shaheryar1** [comment]
Fixed 1 and 3. 
Started working on 2  but it will take some time. I will create a separate PR for highlight effect

**Comment by shaheryar1** [comment]
> markup

Can you send me the original image which you used here? @proofconstruction

**Comment by proofconstruction** [comment]
Sure, here you go
lorem

And here's the file it was generated with, in case you need it:
[lorem.odt](https://github.com/sparkfish/augraphy/files/7315413/lorem.odt)

**Pull request closed without merging**
