### PR TITLE
Update to use Perlin noise instead of Olsen noise in badphotocopy.

### PR DESCRIPTION
**Pull request by kwcckw**

### CODE REVIEW

**Comment by kwcckw** [comment]
To increase the speed, i changed the noise generating algorithm to Perlin noise, it is adapted from here:
https://github.com/pvigier/perlin-numpy

In my machine, it took around 2-3 seconds for each image, and here are some of the examples:
image

Next step would be adding different type of noises (similar with hash type in previous code).

**Comment by proofconstruction** [comment]
Can you revert this commit, pull the latest changes from the main repository, and then add your changes to badphotocopy again?

I just pushed the big update for issue #108

**Comment by proofconstruction** [comment]
[This comment](https://github.com/sparkfish/augraphy/issues/108#issuecomment-939273089) explains the new changes to the project.

**Comment by kwcckw** [comment]
> 
> 
> [This comment](https://github.com/sparkfish/augraphy/issues/108#issuecomment-939273089) explains the new changes to the project.

Thanks, i will go through it and test out those pipelines again later. 

I just pushed, please check again.

**Pull request merged**
