### PR TITLE
Update to increase processing speed of badphotocopy 

### PR DESCRIPTION
**Pull request by kwcckw**

### CODE REVIEW

**Comment by kwcckw** [comment]
With this update, I switched to numpy indexing vectorization and now it took 3 seconds + to run the whole augmentation. I also added `intensity` so that user is able to adjust the noise intensity, for example:

low intensity (darker):
image

high intensity (brighter):
image

**Comment by kwcckw** [comment]
Please take note right now wave pattern is still buggy, i will fix that in the next update.

**Comment by proofconstruction** [comment]
Hmm, the git branches are out of sync again. I did a squash merge of your last PR, and normally I do them to remove the "Merge branch 'dev' of https://github.com/sparkfish/augraphy into dev" commits from the main branch history. How do those commits get created?

I think you'll need to delete your fork and fork again, then apply your most recent commit again.

In the future, when you make "Merge branch 'dev' of https://github.com/sparkfish/augraphy into dev" commits, and then you make a commit (call it `new_commit`) on top of that, can you `git rebase -i HEAD~2` and squash the "Merge branch 'dev'..." commit into `new_commit`? I think this will help me keep a clean git history and also keep our branches in sync.

**Comment by kwcckw** [comment]
> 
> 
> Hmm, the git branches are out of sync again. I did a squash merge of your last PR, and normally I do them to remove the "Merge branch 'dev' of https://github.com/sparkfish/augraphy into dev" commits from the main branch history. How do those commits get created?
> 
> I think you'll need to delete your fork and fork again, then apply your most recent commit again.
> 
> In the future, when you make "Merge branch 'dev' of https://github.com/sparkfish/augraphy into dev" commits, and then you make a commit (call it `new_commit`) on top of that, can you `git rebase -i HEAD~2` and squash the "Merge branch 'dev'..." commit into `new_commit`? I think this will help me keep a clean git history and also keep our branches in sync.

Yea, actually i've been trying to do that but each time it shows merged commit can't be squashed in my github desktop. Usually what i did was pull from "https://github.com/sparkfish/augraphy" before commit any new changes again. At this point, i'm not sure how to prevent this again since there's limited selection in the rebase selection:

image

Do you have any idea on this?

As a temporary measure, i will fork and push again.

**Comment by proofconstruction** [comment]
I'm not sure either, I only use the git CLI, not github desktop. Before you pull the new changes, do you fetch the upstream changes and merge into your fork, using the Github web interface?

It looks like this:
fetchmerge

**Comment by kwcckw** [comment]
> 
> 
> I'm not sure either, I only use the git CLI, not github desktop. Before you pull the new changes, do you fetch the upstream changes and merge into your fork, using the Github web interface?
> 
> It looks like this: fetchmerge

Previously i didn't fetch upstream from my own repo before pull from the root repo, i will try this next time, thanks.

**Pull request closed without merging**
